// Generated by tools/build_arena_layout.py. UTF-8; German glyphs are intentional.
class IsuArenaText
{
	static void Apply(Widget root)
	{
		Label(root, "Subtitle", "Your survivors. Their models. One fight to stay alive.", "Deine Überlebenden. Ihre Modelle. Ein gemeinsamer Überlebenskampf.");
		Label(root, "StatusText", "Ready", "Bereit");
		Label(root, "GrpRoster", "01 / YOUR SURVIVORS", "01 / DEINE GRUPPE");
		Label(root, "RosterNote", "Every field belongs to its survivor. Scroll to see the rest of your group.", "Alle Einstellungen direkt beim Überlebenden. Für weitere Mitglieder nach unten scrollen.");
		Label(root, "BtnAddNpc", "+ ADD SURVIVOR", "+ HINZUFÜGEN");
		Label(root, "GrpRound", "02 / SESSION", "02 / SPIELRUNDE");
		Label(root, "GrpBehavior", "03 / BEHAVIOUR", "03 / VERHALTEN");
		Label(root, "GrpControls", "04 / CONTROLS", "04 / STEUERUNG");
		Label(root, "GrpAudio", "05 / AUDIO & DISPLAY", "05 / AUDIO & ANZEIGE");
		Label(root, "LblMode", "Game mode", "Spielmodus");
		Label(root, "LblSpawn", "Starting position", "Startposition");
		Label(root, "LblCamp", "Camp / click to use your position", "Lager / Klick: aktuelle Position");
		Label(root, "LblMission", "Mission", "Mission");
		Label(root, "LblIdle", "Time between model decisions", "Pause zwischen Modellentscheidungen");
		Label(root, "LblTurns", "Decisions per round", "Entscheidungen pro Runde");
		Label(root, "LblPatrol", "Ambient patrols / applies after server restart", "Umgebungspatrouillen / ab Serverneustart");
		Label(root, "LblOrch", "Group coordination", "Gruppenkoordination");
		Label(root, "LblTarget", "Send commands to", "Befehle richten an");
		Label(root, "LblKeyStop", "Hold position", "Anhalten");
		Label(root, "LblKeyGoto", "Move to target", "Zum Zielpunkt");
		Label(root, "LblKeyRadial", "Command wheel", "Befehlsrad");
		Label(root, "LblMic", "Microphone", "Mikrofon");
		Label(root, "LblComic", "Speech bubbles", "Sprechblasen");
		Label(root, "LblHud", "Squad display (HUD)", "Gruppenanzeige (HUD)");
		Label(root, "LblNpcTts", "Developer mode / NPC radio voices", "Entwicklermodus / NPC-Funkstimmen");
		Label(root, "ModeNote", "Work together and survive as a team.", "Zusammenarbeiten und als Team überleben.");
		Label(root, "OrchNote", "Shared goals, independent decisions.", "Gemeinsame Ziele, eigenständige Entscheidungen.");
		Label(root, "ControlsNote", "Click a key to change its assignment.", "Klicke auf eine Taste, um sie neu zuzuweisen.");
		Label(root, "NpcTtsNote", "Only available in developer mode.", "Nur im Entwicklermodus verfügbar.");
		Label(root, "CostLabel", "SESSION COST", "RUNDENKOSTEN");
		Label(root, "CostText", "No cost recorded yet", "Noch keine Kosten erfasst");
		Label(root, "BtnStop", "STOP", "STOPP");
		Label(root, "HintLine1", "Insert: close menu     /     Right-click camp: reset position     /     Your choices stay selected during this game session.", "Einfg: Menü schließen     /     Rechtsklick auf Lager: Position zurücksetzen     /     Die Auswahl bleibt in dieser Spielsitzung erhalten.");
		Label(root, "RowLblActive", "AI", "KI");
		Label(root, "RowLblName", "NAME", "NAME");
		Label(root, "RowLblProvider", "PROVIDER", "ANBIETER");
		Label(root, "RowLblModel", "MODEL", "MODELL");
		Label(root, "RowLblRole", "ROLE", "ROLLE");
		Label(root, "RowLblLoadout", "LOADOUT", "AUSRÜSTUNG");
		Label(root, "RowLblVoice", "VOICE", "STIMME");
		Label(root, "RowLblLang", "SPEECH LANGUAGE", "AUSGABESPRACHE");
		Label(root, "RowLblLive", "STATUS", "ZUSTAND");
		Label(root, "LiveText", "Ready", "Bereit");
	}

	static void Label(Widget root, string name, string english, string german)
	{
		if (!root) return;
		Widget w = root.FindAnyWidget(name);
		TextWidget label = TextWidget.Cast(w);
		ButtonWidget button = ButtonWidget.Cast(w);
		if (label) label.SetText(IsuUiText.Choose(english, german));
		if (button) button.SetText(IsuUiText.Choose(english, german));
	}

	static void ApplyChoices()
	{
		IsuArenaMenu.s_PersonaLabels.Set(0, IsuUiText.Choose("Hunter", "Jäger"));
		IsuArenaMenu.s_PersonaLabels.Set(1, IsuUiText.Choose("Farmer", "Bauer"));
		IsuArenaMenu.s_PersonaLabels.Set(2, IsuUiText.Choose("Medic", "Sanitäter"));
		IsuArenaMenu.s_PersonaLabels.Set(3, IsuUiText.Choose("Veteran", "Veteran"));
		IsuArenaMenu.s_PersonaLabels.Set(4, IsuUiText.Choose("Fighter", "Kämpfer"));
		IsuArenaMenu.s_LoadoutLabels.Set(0, IsuUiText.Choose("Keep", "Behalten"));
		IsuArenaMenu.s_LoadoutLabels.Set(1, IsuUiText.Choose("Scout", "Späher"));
		IsuArenaMenu.s_LoadoutLabels.Set(2, IsuUiText.Choose("Assault", "Sturm"));
		IsuArenaMenu.s_LoadoutLabels.Set(3, IsuUiText.Choose("Medic", "Sanitäter"));
		IsuArenaMenu.s_LoadoutLabels.Set(4, IsuUiText.Choose("Sniper", "Scharfschütze"));
		IsuArenaMenu.s_LoadoutLabels.Set(5, IsuUiText.Choose("Hunter", "Jäger"));
		IsuArenaMenu.s_LoadoutLabels.Set(6, IsuUiText.Choose("Farmer", "Bauer"));
		IsuArenaMenu.s_LoadoutLabels.Set(7, IsuUiText.Choose("Military", "Militär"));
		IsuArenaMenu.s_LoadoutLabels.Set(8, IsuUiText.Choose("Survivor", "Überlebender"));
		IsuArenaMenu.s_MissionLabels.Set(0, IsuUiText.Choose("No mission", "Keine Mission"));
		IsuArenaMenu.s_MissionLabels.Set(1, IsuUiText.Choose("Mission: Birgit", "Mission: Birgit"));
		IsuArenaMenu.s_MissionLabels.Set(2, IsuUiText.Choose("Event: Horde", "Ereignis: Horde"));
		IsuArenaMenu.s_LangLabels.Set(0, IsuUiText.Choose("German", "Deutsch"));
		IsuArenaMenu.s_LangLabels.Set(1, IsuUiText.Choose("English", "Englisch"));
		IsuArenaMenu.s_LangLabels.Set(2, IsuUiText.Choose("French", "Französisch"));
		IsuArenaMenu.s_LangLabels.Set(3, IsuUiText.Choose("Spanish", "Spanisch"));
		IsuArenaMenu.s_LangLabels.Set(4, IsuUiText.Choose("Italian", "Italienisch"));
		IsuArenaMenu.s_LangLabels.Set(5, IsuUiText.Choose("Portuguese", "Portugiesisch"));
		IsuArenaMenu.s_LangLabels.Set(6, IsuUiText.Choose("Dutch", "Niederländisch"));
		IsuArenaMenu.s_LangLabels.Set(7, IsuUiText.Choose("Polish", "Polnisch"));
		IsuArenaMenu.s_LangLabels.Set(8, IsuUiText.Choose("Russian", "Russisch"));
		IsuArenaMenu.s_LangLabels.Set(9, IsuUiText.Choose("Ukrainian", "Ukrainisch"));
		IsuArenaMenu.s_LangLabels.Set(10, IsuUiText.Choose("Turkish", "Türkisch"));
		IsuArenaMenu.s_LangLabels.Set(11, IsuUiText.Choose("Swedish", "Schwedisch"));
		IsuArenaMenu.s_LangLabels.Set(12, IsuUiText.Choose("Czech", "Tschechisch"));
		IsuArenaMenu.s_LangLabels.Set(13, IsuUiText.Choose("Danish", "Dänisch"));
		IsuArenaMenu.s_LangLabels.Set(14, IsuUiText.Choose("Finnish", "Finnisch"));
		IsuArenaMenu.s_LangLabels.Set(15, IsuUiText.Choose("Greek", "Griechisch"));
		IsuArenaMenu.s_LangLabels.Set(16, IsuUiText.Choose("Romanian", "Rumänisch"));
		IsuArenaMenu.s_LangLabels.Set(17, IsuUiText.Choose("Hungarian", "Ungarisch"));
		IsuArenaMenu.s_LangLabels.Set(18, IsuUiText.Choose("Norwegian", "Norwegisch"));
		IsuArenaMenu.s_LangLabels.Set(19, IsuUiText.Choose("Croatian", "Kroatisch"));
		IsuArenaMenu.s_LangLabels.Set(20, IsuUiText.Choose("Slovak", "Slowakisch"));
		IsuArenaMenu.s_LangLabels.Set(21, IsuUiText.Choose("Japanese", "Japanisch"));
		IsuArenaMenu.s_LangLabels.Set(22, IsuUiText.Choose("Korean", "Koreanisch"));
		IsuArenaMenu.s_LangLabels.Set(23, IsuUiText.Choose("Chinese", "Chinesisch"));
		IsuArenaMenu.s_LangLabels.Set(24, IsuUiText.Choose("Arabic", "Arabisch"));
		IsuArenaMenu.s_LangLabels.Set(25, IsuUiText.Choose("Hindi", "Hindi"));
		IsuArenaMenu.s_LangLabels.Set(26, IsuUiText.Choose("Filipino", "Filipino"));
		IsuArenaMenu.s_CodexLabels.Set(0, IsuUiText.Choose("CLI default", "CLI-Standard"));
		IsuArenaMenu.s_CodexLabels.Set(1, IsuUiText.Choose("5.6 Luna", "5.6 Luna"));
		IsuArenaMenu.s_CodexLabels.Set(2, IsuUiText.Choose("5.6 Terra", "5.6 Terra"));
		IsuArenaMenu.s_CodexLabels.Set(3, IsuUiText.Choose("5.6 Sol", "5.6 Sol"));
		IsuArenaMenu.s_CodexLabels.Set(4, IsuUiText.Choose("6 Astra", "6 Astra"));
		IsuArenaMenu.s_GeminiCliLabels.Set(0, IsuUiText.Choose("CLI default", "CLI-Standard"));
		IsuArenaMenu.s_GeminiCliLabels.Set(1, IsuUiText.Choose("Flash (auto)", "Flash (auto)"));
		IsuArenaMenu.s_GeminiCliLabels.Set(2, IsuUiText.Choose("Pro (auto)", "Pro (auto)"));
		IsuArenaMenu.s_GeminiCliLabels.Set(3, IsuUiText.Choose("Flash-Lite (auto)", "Flash-Lite (auto)"));
		IsuArenaMenu.s_GeminiCliLabels.Set(4, IsuUiText.Choose("3.5 Flash", "3.5 Flash"));
		IsuArenaMenu.s_GeminiCliLabels.Set(5, IsuUiText.Choose("3.1 Pro preview", "3.1 Pro Vorschau"));
		IsuArenaMenu.s_GeminiCliLabels.Set(6, IsuUiText.Choose("3 Flash preview", "3 Flash Vorschau"));
		IsuArenaMenu.s_GeminiCliLabels.Set(7, IsuUiText.Choose("3.1 Flash-Lite", "3.1 Flash-Lite"));
		IsuArenaMenu.s_GeminiCliLabels.Set(8, IsuUiText.Choose("2.5 Pro", "2.5 Pro"));
		IsuArenaMenu.s_GeminiCliLabels.Set(9, IsuUiText.Choose("2.5 Flash", "2.5 Flash"));
		IsuArenaMenu.s_AntigravityLabels.Set(0, IsuUiText.Choose("CLI default", "CLI-Standard"));
		IsuArenaMenu.s_AntigravityLabels.Set(1, IsuUiText.Choose("Gemini 3.8 Flash (High)", "Gemini 3.8 Flash (Hoch)"));
		IsuArenaMenu.s_AntigravityLabels.Set(2, IsuUiText.Choose("Gemini 3.8 Flash (Medium)", "Gemini 3.8 Flash (Mittel)"));
		IsuArenaMenu.s_AntigravityLabels.Set(3, IsuUiText.Choose("Gemini 3.8 Flash (Low)", "Gemini 3.8 Flash (Niedrig)"));
		IsuArenaMenu.s_AntigravityLabels.Set(4, IsuUiText.Choose("Gemini 3.7 Flash (High)", "Gemini 3.7 Flash (Hoch)"));
		IsuArenaMenu.s_AntigravityLabels.Set(5, IsuUiText.Choose("Gemini 3.7 Flash (Medium)", "Gemini 3.7 Flash (Mittel)"));
		IsuArenaMenu.s_AntigravityLabels.Set(6, IsuUiText.Choose("Gemini 3.7 Flash (Low)", "Gemini 3.7 Flash (Niedrig)"));
		IsuArenaMenu.s_AntigravityLabels.Set(7, IsuUiText.Choose("Gemini 3.6 Flash (High)", "Gemini 3.6 Flash (Hoch)"));
		IsuArenaMenu.s_AntigravityLabels.Set(8, IsuUiText.Choose("Gemini 3.6 Flash (Medium)", "Gemini 3.6 Flash (Mittel)"));
		IsuArenaMenu.s_AntigravityLabels.Set(9, IsuUiText.Choose("Gemini 3.6 Flash (Low)", "Gemini 3.6 Flash (Niedrig)"));
		IsuArenaMenu.s_AntigravityLabels.Set(10, IsuUiText.Choose("Gemini 3.1 Pro (High)", "Gemini 3.1 Pro (Hoch)"));
		IsuArenaMenu.s_AntigravityLabels.Set(11, IsuUiText.Choose("Gemini 3.1 Pro (Low)", "Gemini 3.1 Pro (Niedrig)"));
		IsuArenaMenu.s_AntigravityLabels.Set(12, IsuUiText.Choose("Claude Sonnet 4.6 (Thinking)", "Claude Sonnet 4.6 (Thinking)"));
		IsuArenaMenu.s_AntigravityLabels.Set(13, IsuUiText.Choose("Claude Opus 4.6 (Thinking)", "Claude Opus 4.6 (Thinking)"));
		IsuArenaMenu.s_AntigravityLabels.Set(14, IsuUiText.Choose("GPT-OSS 120B (Medium)", "GPT-OSS 120B (Mittel)"));
	}
}
